<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <WindowsPackageType>None</WindowsPackageType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <SelfContained>false</SelfContained>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Assets/app.ico" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Assets/connected.ico" />
    <EmbeddedResource Include="Assets/disconnected.ico" />
    <None Include="../../README.md" Link="README.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../config.example.yaml" Link="config.example.yaml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="2.3.9" />
    <PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.6" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Runtime" Version="2.4.0" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
</Project>
